//next import
import Head from "next/head";

//stylesheet import
import styles from "@/styles/Home.module.css";

//components import
import Homepage from "@/Components/Homepage/Homepage";

export default function Home() {
  return (
    <>
      <Head>
        <title>SimpliHR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          http-equiv="Content-Security-Policy"
          content="upgrade-insecure-requests"
        ></meta>
      </Head>
      <Homepage />
    </>
  );
}
